server:
  port: 9090
spring:
  application:
    name: dubbo-consumer
#可以使用${}表达式去引入
user:
  service:
    version: 1.0.0

dubbo:
  #扫描duubo的注解，此处是@Service的注解
  scan:
    basePackages: com.cheungyutong.controller
  #dubbo config
  application:
    id: dubbo-consumer
    name: dubbo-consumer
    #端口开始占用了22222，所以这增加一个，此外这qos相关配置完全可以不使用
    #qos-port: 22223
    #qos-enable: true
  #protocl config
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
  #registry config
  registry:
    id: zookeeper
    #如果是集群zookeeper://39.106.151.228:2181?backup=39.106.151.228:2181,39.106.151.228:2181
    address: zookeeper://39.106.151.228:2181
#dubbo状态检查
management:
  endpoint:
    dubbo:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-properties:
      enabled: true
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool